Add expiration_date to Users
cesium-ml/baselayer pull request #233
Opened 2021-06-23 19:00 UTC by kmshin1397

Also changed the `is_active` function for Users, which currently is just returning `True` no matter what, so that it serves as a check for expired users. We don't seem to be using this function anywhere, but doesn't hurt to have it be more of a real function in case we use it later. This will be accompanied by a PR on SkyPortal to actually use the new column for user expiration functionality (setting expired users to view only automatically). Part of addressing fritz-marshal/fritz#180

Plus black formatting.

2021-06-23 19:00 UTC, pep8speaks commented
Hello @kmshin1397! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`app/models.py`](https://github.com/cesium-ml/baselayer/blob/0d281aadf8f42d461ec28cfb5fb44d4f4c87faff/app/models.py):

> [Line 1271:80](https://github.com/cesium-ml/baselayer/blob/0d281aadf8f42d461ec28cfb5fb44d4f4c87faff/app/models.py#L1271): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (108 > 79 characters)

2021-06-23 19:04 UTC, acrellin approved these changes

2021-06-23 19:08 UTC, acrellin commented
This all looks good, but one note for the SP PR: it feels more intuitive to have a user expiration date and the active/inactive flag correspond to deactivating the account altogether rather than just making them view only. But I guess that'll have to be decided by the PIs.

2021-06-23 19:11 UTC, kmshin1397 commented
> This all looks good, but one note for the SP PR: it feels more intuitive to have a user expiration date and the active/inactive flag correspond to deactivating the account altogether rather than just making them view only. But I guess that'll have to be decided by the PIs.

Ah yeah, that makes sense and we can discuss that further. I think the view only way was the easier path of implementation, since I imagine completely deactivating accounts will mean implementing a new "Deactivated accounts" table for the user management page, maybe blocking inactive accounts from logging in, canceling their API tokens, etc. I just saw less steps to simply setting them to view only but definitely wiling to change directions here.

2021-06-25 19:57 UTC, kmshin1397 commented
Instead of adding another flag column, I just used the existing `User.is_active()` function mentioned above to use to guard against expired users doing anything on the API. This guard logic has been incorporated into `access.py`

2021-06-25 20:02 UTC, acrellin approved these changes
Nice!

2021-06-25 20:03 UTC, acrellin requested changes
Ah just realized we'll also need to add the check to the `permissions` decorator here, especially since we'll no longer be removing ACLs

2021-06-25 20:05 UTC, acrellin approved these changes
Haha, my bad, I see that permissions is already decorated with auth_or_token!

2021-06-30 18:16 UTC, stefanv approved these changes
Looks good.

I see we used `403` before where we probably should have used `401`.  Do you mind fixing that in this PR?

2021-06-30 18:16 UTC, stefanv commented on app/access.py
>                  raise tornado.web.HTTPError(403)
Should this be 401?

2021-06-30 18:28 UTC, kmshin1397 commented on app/access.py
>                  raise tornado.web.HTTPError(403)
Agreed, this has been changed

2021-06-30 18:31 UTC, stefanv commented
@kmshin1397 Sorry, I may not have been clear: *Your* implementation was correct, we just needed to switch the code on the *old* one.  I.e., 401 if the token is not recognized and 403 if the token is valid (user is recognized) but access is forbidden.

2021-06-30 18:34 UTC, kmshin1397 commented
Ah right okay yes I see the difference between the two now. _Now_ it should be fixed

2021-06-30 18:36 UTC, merged

2021-06-30 18:36 UTC, stefanv commented
Thanks, Kyung!