Aliasing like that does not work for sqlalchemy >= 1.4
cesium-ml/baselayer pull request #267
Opened 2021-12-21 16:54 UTC by mcoughlin

Allows the permissions checking to pass in sqlalchemy >= 1.4.

See: https://docs.sqlalchemy.org/en/14/changelog/migration_14.html
in particular: Built-in FROM linting will warn for any potential cartesian products in a SELECT statement

2021-12-21 17:05 UTC, pep8speaks commented
Hello @mcoughlin! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`app/handlers/base.py`](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/handlers/base.py):

> [Line 124:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/handlers/base.py#L124): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 138:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/handlers/base.py#L138): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 199:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/handlers/base.py#L199): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 201:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/handlers/base.py#L201): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 268:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/handlers/base.py#L268): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 305:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/handlers/base.py#L305): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 309:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/handlers/base.py#L309): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 374:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/handlers/base.py#L374): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)

* In the file [`app/models.py`](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/models.py):

> [Line 361:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/models.py#L361): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 372:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/models.py#L372): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 679:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/models.py#L679): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 683:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/models.py#L683): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 992:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/models.py#L992): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 1110:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/models.py#L1110): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 1147:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/models.py#L1147): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 1161:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/models.py#L1161): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 1168:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/models.py#L1168): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 1199:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/models.py#L1199): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 1200:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/models.py#L1200): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 1204:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/models.py#L1204): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 1209:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/models.py#L1209): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 1252:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/models.py#L1252): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 1326:80](https://github.com/cesium-ml/baselayer/blob/cec4ba94da5b2d2c0de9f66b18a9f5667996f292/app/models.py#L1326): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)

2021-12-21 17:29 UTC, mcoughlin commented
@stefanv @profjsb I don't have workflow powers.

2021-12-21 18:05 UTC, profjsb commented
> @stefanv @profjsb I don't have workflow powers.

Done. And added you with enhanced powers to this repo.

2022-01-06 16:59 UTC, profjsb requested changes
Unfortunately the linting made this PR look longer than it really is.  My main question is whether using `sa.select` in place of `DBSession().query` could cause leakage across users since the query will not be done in scoped session. Or perhaps the role of this change is only to facilitate the `construction` of the query itself, not the issuance of the query (which must be done in a scoped session). @stefanv thoughts?

Please revert the token constraint change as noted in the inline comments.

2022-01-06 16:59 UTC, profjsb commented on app/models.py
> +        unique=True,
I think this needs to get removed -- Token names can be identical for different users.

2022-01-06 16:59 UTC, profjsb commented on app/models.py
> -    __table_args__ = (sa.UniqueConstraint("created_by_id", "name", name="token_name_userid_unique_constraint"),)
reinstate: we need to create a unique constraint on id+name.
See https://github.com/cesium-ml/baselayer/pull/262/files

2022-01-06 17:53 UTC, mcoughlin commented
@stefanv https://github.com/cesium-ml/baselayer/pull/267/files#diff-90c680eba43456b516da8b4c2573d467ae17d1b0ed4373549f2a593ced3616d5L623
These lines here.

2022-01-08 07:39 UTC, mcoughlin commented
@profjsb Minimal PR is now here

2022-01-16 00:53 UTC, profjsb commented
merging this into it's own branch on cesium-ml/baselayer so we can try it out on SP.

2022-01-16 00:54 UTC, merged

2022-01-16 01:57 UTC, stefanv commented
Do we know whether it is safe to remove this? There's a comment abusive it which states its purpose, so would be good to understand its original intent.

2022-01-16 02:27 UTC, mcoughlin commented
Reading the 1.3 to 1.4 docs it seems like they made some changes to how aliases were handled, but presumably Danny needs to comment why it was there in the first place.